services:
  keycloak_db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bionicnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      keycloak_db:
        condition: service_healthy
    networks:
      - bionicnet

  bionicpro-auth:
    build: ./bionicpro-auth
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Keycloak__Authority: http://keycloak:8080/realms/reports-realm
      Keycloak__TokenUrl: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/token
      Keycloak__LogoutUrl: http://keycloak:8080/realms/reports-realm/protocol/openid-connect/logout
      Keycloak__ClientId: bionicpro-auth
      Keycloak__ClientSecret: VBS1hiAlCWwSIDN41hEUn7WfrNogPSAU
      Session__TimeoutMinutes: 120
    ports:
      - "5001:80"
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - bionicnet

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_AUTH_API_URL=http://localhost:5001/api/auth
      - REACT_APP_BUSINESS_API_URL=http://localhost:5001/api
    ports:
      - "3000:80"
    depends_on:
      - bionicpro-auth
    networks:
      - bionicnet
    
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldif
    environment:
      LDAP_ORGANISATION: "BionicPRO"
      LDAP_DOMAIN: "bionicpro.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "admin"
    volumes:
      - ./ldif/data:/var/lib/ldap
      - ./ldif/config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    networks:
      - bionicnet
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost:389 -D 'cn=admin,dc=bionicpro,dc=com' -w admin -b 'dc=bionicpro,dc=com'"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  bionicnet:
    driver: bridge